services:
  - couchdb
notifications:
  email: false
before_script:
  - "config/ci/travis/setup_couch.sh"
  - "mv config/ci/travis/couchdb.admin.yml config/couchdb.admin.yml"
  - "mv config/ci/travis/couchdb.yml config/couchdb.yml"
  - "bundle exec rake RAILS_ENV=test db:rotate"
  - "bundle exec rake RAILS_ENV=test db:migrate"
after_script:
  - "cat tmp/*.test*.log" # printing logs from the failed integration tests
bundler_args: --without development debug
