dev_ca: &dev_ca
  client_ca_key: "./certs/test/files/ca.key"
  client_ca_cert: "./certs/test/files/ca.crt"
  ca_key_password: nil

cert_options: &cert_options
  client_cert_lifespan: 2
  client_cert_bit_size: 2024
  client_cert_hash: "SHA256"
  allow_limited_certs: false
  allow_unlimited_certs: true
  allow_anonymous_certs: false
  limited_cert_prefix: "LIMITED"
  unlimited_cert_prefix: "UNLIMITED"

downloads: &downloads
  client_download_domain: https://downloads.leap.se
  available_clients:
    - linux32
    - linux64
    - mac
    - windows
    - android
  download_paths:
    android: /client/android
    linux:   /client/linux
    linux32: /client/linux/Bitmask-linux32-latest.tar.bz2
    linux64: /client/linux/Bitmask-linux64-latest.tar.bz2
    osx:     /client/osx/Bitmask-OSC-latest.dmg
    windows: /client/windows
    other:   /client

common: &common
  force_ssl: false
  pagination_size: 30
  auth:
    token_expires_after: 60
  # handles that will be blocked from being used as logins or email aliases
  # in addition to the ones in /etc/passwd and http://tools.ietf.org/html/rfc2142
  handle_blacklist: [certmaster, ssladmin, arin-admin, administrator, www-data, maildrop]
  # handles that will be allowed despite being in /etc/passwd or rfc2142
  handle_whitelist: []


development:
  <<: *downloads
  <<: *dev_ca
  <<: *cert_options
  <<: *common
  admins: [blue, admin, admin2]
  domain: example.org
  secret_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  payment: []

test:
  <<: *downloads
  <<: *dev_ca
  <<: *cert_options
  <<: *common
  admins: [admin, admin2]
  domain: test.me
  secret_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  payment: [billing]

production:
  <<: *downloads
  <<: *cert_options
  <<: *common
  admins: []
  domain: example.net
  payment: []
  # logfile: /path/to/your/logs
